Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Enabled: false

Style/Encoding:
  Enabled: false

Documentation:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
